//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập FistName ")]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "Chiều dài phải từ 2 đến 20 chữ")]
        public string FistName { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập LastName")]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "Chiều dài phải từ 2 đến 20 chữ")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập email")]
        [EmailAddress]
        public string Email { get; set; }
       //[Required(ErrorMessage ="Bạn chưa nhập Password")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Bạn chưa nhập Password")]
        [StringLength(100, ErrorMessage = "{0} dài từ {2} đến {1} ký tự.", MinimumLength = 5)]
        public string Password { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập Phone")]
        [Phone(ErrorMessage = "Số điện thoại không hợp lệ")]
        [StringLength(12, MinimumLength = 10, ErrorMessage = "Chiều dài phải từ 10 đến 12 số")]

        public string Phone { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập địa chỉ")]
        public string Address { get; set; }
    }
}
